import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "./components/Navbar";
import Footer from "./components/Footer";
import { AuthProvider } from "./_context/AuthContext";
// import apiFetch from "@/lib/apiFetch";
import apiServer from "@/lib/apiServer";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Remote Shop",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }) {
  const response = await apiServer("profile");
  // console.log(response);
  // if(response.ok){
  //   const user = await response.json();
  // } 
  // else{
  //   const user = null;
  // }
  const user = response.ok? await response.json(): null;
  // console.log(user);
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        <AuthProvider initialUser={user}>
          <Navbar></Navbar>
          <div>
            {children}
          </div>
        </AuthProvider>
        <Footer/>
      </body>
    </html>
  );
}
